name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Get commit details
        id: commit_info
        run: |
          echo ::set-output name=commit_count::$(git rev-list --count ${{ github.event.before }}..${{ github.event.after }} || echo 0)
          COMMIT_LOG=$(git log --pretty=format:"%h %s" --abbrev-commit ${{ github.event.before }}..${{ github.event.after }} || echo null)
          COMMIT_LOG="${COMMIT_LOG//'%'/'%25'}"
          COMMIT_LOG="${COMMIT_LOG//$'\n'/'%0A'}"
          COMMIT_LOG="${COMMIT_LOG//$'\r'/'%0D'}"
          echo ::set-output name=commit_log::$COMMIT_LOG

      - name: Send a message about the latest commit
        run: |
          curl \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d disable_notification=true \
          -d parse_mode=HTML \
          --data-urlencode "text=\
          ↗️ <b>PUSH</b>
          <b>was made at:</b> ${{ github.repository }}
          <b>by:</b> <u>${{ github.actor }}</u>
          <b>commits pushed:</b> ${{ steps.commit_info.outputs.commit_count }}
          <b>commit log:</b>
          <pre>${{ steps.commit_info.outputs.commit_log }}</pre>
          
          <b>url:</b> https://github.com/${{ github.repository }}/commit/${{ github.sha }}" \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    env:
      API_ENDPONT: ""
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install packages
      run: 'npm install'

    - name: Build APP
      run: 'npm run build'


    - name: Deploy to Cloudflare Workers with Wrangler
      uses: cloudflare/wrangler-action@1.1.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}